spring:
  config:
    activate:
      on-profile: "datasource"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
    hikari:
      maximum-pool-size: 10 # default
      connection-timeout: 250 #3000 30 seconds in milliseconds
      keepalive-time: 600000 # 5 minutes in milliseconds
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000

logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

