spring:
  profiles:
    active: ${profile}
    group:
      local: "local, datasource"
      dev: "dev"
      prod: "prod"
    include:
      - aws
      - security
  mvc:
    ignore-default-favicon: true

cors-allowed-origins:
  http://localhost:8080,
  https://dev.math-pointer.com,
  http://dev.math-pointer.com,
  https://prod.math-pointer.com,
  http://prod.math-pointer.com,
  
  http://localhost:3000,
  http://localhost:5173,
  https://ppp.admin.math-pointer.com,
  http://ppp.admin.math-pointer.com,
  https://ppp.dev.admin.math-pointer.com,
  http://ppp.dev.admin.math-pointer.com,
  https://www.math-pointer.com,
  http://www.math-pointer.com,
  https://www.dev.math-pointer.com
  http://www.dev.math-pointer.com


